/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConfigForm: typeof import('./components/ConfigForm.vue')['default']
    FormWrapper: typeof import('./components/FormWrapper.vue')['default']
    HiArrowRight: typeof import('~icons/humbleicons/arrow-right')['default']
    HiCode: typeof import('~icons/humbleicons/code')['default']
    HiCpu: typeof import('~icons/humbleicons/cpu')['default']
    HiPower: typeof import('~icons/humbleicons/power')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
  }
}
